HockeyPT/HockeyPT/Models/Jogadores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace HockeyPT.Models
{
    public class Jogadores
    {
        [Key]
        public int ID { get; set; }

        //Dados do Jogador

        public string Nome { get; set; }

        public string Posicao { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd}", ApplyFormatInEditMode = true)]
        [DataType(DataType.Date)]
        [Display(Name = "Data de Nascimento")]
        public DateTime DataNascimento { get; set; }

        public string Nacionalidade { get; set; }

        public int Altura { get; set; }

        public int Peso { get; set; }

        public string Fotografia { get; set; }

        //Construção da Chave Forasteira
        [ForeignKey("Equipa")]
        public int EquipaPK { get; set; }
        public virtual Equipas Equipa { get; set; }
    }
}

HockeyPT/HockeyPT/Controllers/JogadoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HockeyPT.Models;
using IdentitySample.Models;

namespace HockeyPT.Controllers
{
    public class JogadoresController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jogadores
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            var listaDeJogadores = db.Jogadores.OrderBy(j => j.ID).ToList();
            return View(listaDeJogadores);
        }
        //***************************************************DETAILS*************************************************************
        // GET: Jogadores/Details/5
        /// <summary>
        /// Apresenta os detalhes de um jogador
        /// </summary>
        /// <param name="id">apresenta a PK que identifica o Jogador</param>
        /// <returns></returns>
        //[Authorize(Roles = "Administrador")]
        public ActionResult Details(int? id)
        {
            //protege a execução do método contra a não existência de valores nulos
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }

            //vai procurar o jogador cujo ID foi fornecido
            Jogadores jogadores = db.Jogadores.Find(id);

            //se esse jogador não for encontrado
            if (jogadores == null)
            {
                //return HttpNotFound();
                return RedirectToAction("Index");
            }
            
            //envia para a View os dados do Jogador
            return View(jogadores);
        }

        //*************************************************************CREATE***************************************************
        // GET: Jogadores/Create
        /// <summary>
        /// GET: Jogadores/Create
        /// </summary>
        /// <param name="EquipaFK"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrador")]
        public ActionResult Create(int EquipaFK)
        {
            ViewBag.EquipaPK = new SelectList(db.Equipas, "ID", "Nome");
            Session["EquipaFK"] = EquipaFK;
            return View();
        }


        // POST: Jogadores/Create
        /// <summary>
        /// Método que permite criar um jogador e enviar para o servidor
        /// </summary>
        /// <param name="jogadores"></param>
        /// <param name="carregaFotografia"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Create([Bind(Include = "Nome,Posicao,DataNascimento,Nacionalidade,Altura,Peso,Fotografia")] Jogadores jogadores,
                                    HttpPostedFileBase carregaFotografia){
            //determinar o ID do novo Jogador
            int novoIDJogador = 0;
            //determinar o numero de Jogadores na tabela
            //caso a tabela dos jogadores esteja vazia
            if (db.Jogadores.Count() == 0)
            {
                //o ID no novo jogador será 1
                novoIDJogador = 1;
            }
            //caso a tabela contenha jogadores
            else
            {
                //o novo ID sera o numero maximo do ID existente + 1
                novoIDJogador = db.Jogadores.Max(j => j.ID) + 1;
            }
            //atribuição do novo ID ao jogador
            jogadores.ID = novoIDJogador;
            //atribuiçao da EquipaFK ao jogador
            jogadores.EquipaPK = (int)Session["EquipaFK"];
            string nomeFotografia = "Jogadores_" + novoIDJogador + ".jpg";
            string caminhoFotografia = "";      

            if (carregaFotografia != null)
            {
                //Verificar se o ficheiro é uma imagem
                if (carregaFotografia.ContentType.Contains("image"))
                {
                    //Definir o nome da Capa
                    jogadores.Fotografia = nomeFotografia;
                    //guardar na variavel auxiliar o caminho para onde guardar a imagem
                    caminhoFotografia = Path.Combine(Server.MapPath("~/JogadoresFotos/"), nomeFotografia); // indica onde a imagem será guardada
                }
                else
                {
                    ModelState.AddModelError("", "O ficheiro inserido não é nenhuma imagem!");
                }

            }
            //ficheiro nao inserido
            else
            {
                //gerar mensagem de erro para indicar o utilizador que nao foi inserida nenhuma imagem
                ModelState.AddModelError("", "Não foi inserida uma imagem");
                //redirecionar o utilizador para a View
                return View(jogadores);

            }

            //ModelSatete.IsValid -> confronta os dados fornecidos com o modelo
            //se nao respeitar as regra dos modelo, rejeita os dados
            if (ModelState.IsValid)
            {
                try
                {
                    //adiciona na estrutura de dados, na memoria do servidor, o objeto Jogadores
                    db.Jogadores.Add(jogadores);
                    //faz commit na base de dados
                    db.SaveChanges();
                    //guarda a imagem no disco rigido
                    carregaFotografia.SaveAs(caminhoFotografia);
                    //redireciona o utilizador para a pagina inicial
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    //gera uma mensagem de erro para o utilizador
                    ModelState.AddModelError("", "Ocorreu um erro na criação de um jogador ");
                }
            }

            ViewBag.EquipaPK = new SelectList(db.Equipas, "ID", "Nome");
            return View(jogadores);
        }

        //*****************************************************EDIT******************************************************
        // GET: Jogadores/Edit/5
        /// <summary>
        /// GET: Jogadores/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");
            }
            Jogadores jogadores = db.Jogadores.Find(id);
            if (jogadores == null)
            {
                //return HttpNotFound();
                return RedirectToAction("Index");
            }
            ViewBag.EquipaPK = new SelectList(db.Equipas, "ID", "Nome", jogadores.EquipaPK);
            return View(jogadores);
        }

        // POST: Jogadores/Edit/5
        /// <summary>
        /// Método que permite editar um jogador
        /// </summary>
        /// <param name="jogador"></param>
        /// <param name="ficheiroFotografiaJogador"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit([Bind(Include = "ID,Nome,Posicao,DataNascimento,Nacionalidade,Altura,Peso,Fotografia,EquipaPK")] Jogadores jogador,
                                 HttpPostedFileBase ficheiroFotografiaJogador)
        {
            //variaveis auxiliares
            string novoNome = "";
            string nomeAntigo = "";
            DateTime dataAtual = DateTime.Now;

            //try
            //{
                //caso a data de nascimento seja maior que a atual
                if (jogador.DataNascimento >= dataAtual)
                {
                    ModelState.AddModelError("", "Erro na data de nascimento!");
                    return View(jogador);
               }


            if (ModelState.IsValid)
            {
                try
                {
                    if (ficheiroFotografiaJogador != null)
                    {
                        if (ficheiroFotografiaJogador.ContentType.Contains("image/"))
                        {
                            nomeAntigo = jogador.Fotografia;
                            novoNome = "Jogador_" + jogador.ID + DateTime.Now.ToString("_yyyyMMdd_hhmmss") + Path.GetExtension(ficheiroFotografiaJogador.FileName).ToLower(); ;
                            jogador.Fotografia = novoNome;
                            ficheiroFotografiaJogador.SaveAs(Path.Combine(Server.MapPath("~/JogadoresFotos/"), novoNome));
                        }
                        else
                        {
                            ModelState.AddModelError("", "Erro ao inserir imagem, ficheiro não é uma imagem!");
                            return View(jogador);
                        }
                    }

                    db.Entry(jogador).State = EntityState.Modified;
                    db.SaveChanges();

                    if (ficheiroFotografiaJogador != null && ficheiroFotografiaJogador.ContentType.Contains("/image"))
                    {
                       System.IO.File.Delete(Path.Combine(Server.MapPath("~/JogadoresFotos/"), nomeAntigo));
                    }

                    return RedirectToAction("Details", "Equipas", new { id = jogador.EquipaPK });
                }
                catch (Exception)
                {
                    // caso haja um erro deve ser enviada uma mensagem para o utilizador
                    ModelState.AddModelError("", string.Format("Ocorreu um erro com a edição dos dados do jogador {0}", jogador.Nome));
                }
            }
            return View(jogador);
        }

HockeyPT/HockeyPT/Views/Jogadores/Create.cshtml
@model HockeyPT.Models.Jogadores

@{
    ViewBag.Title = "Criar Equipas";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Create","Jogadores",FormMethod.Post, new { enctype = "multipart/form-data"}))
    {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <br />
        <h3 style="color:darkcyan"> Criar um novo jogador </h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Posição", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Data de Nascimento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Altura em cm's", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Peso em kg's", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @* @Html.EditorFor(model => model.Fotografia, new { htmlAttributes = new { @class = "form-control" } })*@
                <input type="file"
                       name="carregaFotografia"
                       style="color:blue;"
                       accept=".jpg" />
                @Html.ValidationMessageFor(model => model.Fotografia, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
               
            </div>
        </div>
    </div>
    }
    
</body>
</html>

HockeyPT/HockeyPT/Views/Jogadores/Delete.cshtml
@model HockeyPT.Models.Jogadores

@{
    ViewBag.Title = "Delete";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

    <div>
        <h3 style="color:brown">Tem a certeza que pretende eliminar o jogador?</h3>
       


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Apagar" class="btn btn-danger" /> 
                <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Details", "Equipas", new { id = Model.EquipaPK })'"> Cancelar </button>
            </div>
        }
    </div>
</body>
</html>

HockeyPT/HockeyPT/Views/Jogadores/Details.cshtml
@model HockeyPT.Models.Jogadores

@{
    ViewBag.Title = "DetailsJogador";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <h3 style="font-family:Arial;margin-top:40px">@Html.DisplayFor(model => model.Nome)</h3>
    <hr class="estilo2" />

    <div style="display:flex">
        <a href="~/JogadoresFotos/@Model.Fotografia" target="_blank">
            <img src="~/JogadoresFotos/@Model.Fotografia" width="270" height="409"  style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);margin-left:30px"/>
        </a>

        <div class="detalhesJogadorEsq" style="margin-left:30px">
            <h3 style="margin-bottom:0px">Nome do Jogador:</h3>
            <p>@Html.DisplayFor(model => model.Nome)</p>
            
            <h3 style="margin-bottom:0px"> Data de Nascimento:</h3>
            <p>@Html.DisplayFor(model => model.DataNascimento)</p>
            
            <h3 style="margin-bottom:0px"> Nacionalidade do Jogador:</h3>
            <p>@Html.DisplayFor(model => model.Nacionalidade)</p>
            <h3 style="margin-bottom:0px"> Altura do Jogador:</h3>
            <p>@Html.DisplayFor(model => model.Altura) cm's</p>

        </div>
        <div class="detalhesJogadorDir" style="float:right; margin-left:30px">
            <h3 style="margin-bottom:0px"> Posição do Jogador:</h3>
            <p>@Html.DisplayFor(model => model.Posicao)</p>
            <h3 style="margin-bottom:0px"> Nacionalidade do Jogador:</h3>
            <p>@Html.DisplayFor(model => model.Nacionalidade)</p>
            <h3 style="margin-bottom:0px"> Peso do Jogador:</h3>
            <p>@Html.DisplayFor(model => model.Peso) kg's</p>

        </div>
    </div>

    @if (User.IsInRole("Administrador") || User.IsInRole("Moderador"))
    {
        <div style="margin-top:20px ">
            <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Edit","Jogadores",new { id = Model.ID })'">Editar</button>
            <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Delete","Jogadores",new { id = Model.ID })'">Apagar</button>
        </div>


    }

    <div style="margin-top:20px">
        <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Details","Equipas", new { id = Model.EquipaPK })'"> Voltar ao Inicio </button>
    </div>
    



</body>
</html>

HockeyPT/HockeyPT/Views/Jogadores/Edit.cshtml
@model HockeyPT.Models.Jogadores

@{
    ViewBag.Title = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")

    @using (Html.BeginForm("Edit",
                            "Jogadores",
                            FormMethod.Post,
                            new {enctype= "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <br />
        <h3 style="color:darkcyan"> Editar Jogador </h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Fotografia)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Posição", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Posicao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Posicao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Data de Nascimento", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataNascimento, new { htmlAttributes = new { @class = "form-control", @type = "date" } })
                @Html.ValidationMessageFor(model => model.DataNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nacionalidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nacionalidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nacionalidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Altura em cm's", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Altura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Altura, "", new { @class = "text-danger" })           
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Peso em kg's", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fotografia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @* Mostrar a imagem associada ao Jogador *@
                <a href="~/JogadoresFotos/@Model.Fotografia" target="_blank">
                    <img src="~/JogadoresFotos/@Model.Fotografia" height="150" />
                </a>

                @* procurar a nova imagem*@
                <input type="file" name="ficheiroFotografiaJogador" style="color:blue;" accept=".jpg" />
            </div>
        </div>
        @Html.HiddenFor(c=>c.EquipaPK)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
                <button type="button" class="btn btn-default" style="margin-bottom:0px" onclick="location.href='@Url.Action("Details", "Equipas", new { id = Model.EquipaPK })'"> Cancelar </button>
            </div>
        </div>
    </div>
    }


</body>
</html>

HockeyPT/HockeyPT/Views/Jogadores/Index.cshtml
@model IEnumerable<HockeyPT.Models.Jogadores>

@{
    ViewBag.Title = "Jogadores";
}

<h1> Lista de Jogadores </h1>
                                                                                    
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Criar Novo Jogador", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fotografia)
            </th>
            
        </tr>
    
    @foreach (var jogadores in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => jogadores.Nome)
            </td>
            
            <td>
                @*@Html.DisplayFor(modelItem => item.Fotografia)*@
                
                <a href="~/JogadoresFotos/@jogadores.Fotografia" target="_blank">
                    <img src="~/JogadoresFotos/@jogadores.Fotografia" width="50" height="70"/>
                </a>
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id = jogadores.ID }) |
                @Html.ActionLink("Detalhes", "Details", new { id = jogadores.ID }) |
                @Html.ActionLink("Apagar", "Delete", new { id = jogadores.ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>