HockeyPT/HockeyPT/Models/Equipas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HockeyPT.Models
{
    public class Equipas
    {
        public Equipas()
        { 
            ListaDeNoticias = new HashSet<Noticias>();
            ListaDeJogadores = new HashSet<Jogadores>();
        }

        [Key]
        public int ID { get; set; }

        public string Nome { get; set; }

        public string Logotipo { get; set; }

        public string Cidade { get; set; }
        
        public virtual ICollection<Noticias> ListaDeNoticias { get; set; }

        public virtual ICollection<Jogadores> ListaDeJogadores { get; set; }

    }
}

HockeyPT/HockeyPT/Controllers/EquipasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HockeyPT.Models;
using IdentitySample.Models;

namespace HockeyPT.Controllers
{
    public class EquipasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Equipas
        [Authorize(Roles = "Administrador")]
        public ActionResult Index()
        {
            var listaDeEquipas = db.Equipas.OrderBy(e => e.ID).ToList();
            return View(listaDeEquipas);
        }

        //*************************************DETAILS****************************************************************
        // GET: Equipas/Details/5
        /// <summary>
        ///  Método que apresenta detalhes das equipas
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {
            //caso o valor do id seja nulo
            if (id == null)
            {
                //redirecciona para a pagina inicial
                return RedirectToAction("Index");

            }
            //vai procurar o ID da Equipa fornecido
            Equipas equipas = db.Equipas.Find(id);

            //se a Equipa nao for encontrada
            if (equipas == null)
            {
                //redirecciona para o Index
                return RedirectToAction("Index");
            }

            //envia para  a view os dados da Equipa 
            return View(equipas);
        }
        public ActionResult ListarEquipas()
        {
            var model = db.Equipas.ToList();
            return PartialView(model);
        }


        //**************************************************************EDIT*******************************************
        // GET: Equipas/Edit/5
        /// <summary>
        /// GET: Equipas/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Index");

            }
            Equipas equipas = db.Equipas.Find(id);
            if (equipas == null)
            {
                //return HttpNotFound();
                return RedirectToAction("Index");
            }
            return View(equipas);
        }

        // POST: Equipas/Edit/5
        /// <summary>
        /// Método que permite editar uma equipa e enviar respostas para o servidor
        /// </summary>
        /// <param name="equipa"></param>
        /// <param name="novoLogotipo"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit([Bind(Include = "ID,Nome,Logotipo,Cidade")] Equipas equipa,
                                 HttpPostedFileBase novoLogotipo)
        {
            //variaveis auxiliares
            string novoNome = "";
            string nomeAntigo = "";

            if (ModelState.IsValid)
            {
                try
                {
                    if (novoLogotipo != null)
                    {
                        if (novoLogotipo.ContentType.Contains("image/")) { 
                            nomeAntigo = equipa.Logotipo;
                            novoNome = "Equipa" + equipa.ID + DateTime.Now.ToString("_yyyyMMdd_hhmmss") + Path.GetExtension(novoLogotipo.FileName).ToLower(); ;
                            equipa.Logotipo = novoNome;
                            novoLogotipo.SaveAs(Path.Combine(Server.MapPath("~/EquipasFotos/"), novoNome));
                        }
                        else
                        {
                            ModelState.AddModelError("", "Erro ao inserir imagem, ficheiro não é uma imagem!");
                            return View(equipa);
                        }
                    }

                    db.Entry(equipa).State = EntityState.Modified;
                    db.SaveChanges();

                    if (novoLogotipo != null && novoLogotipo.ContentType.Contains("/image"))
                    {
                        System.IO.File.Delete(Path.Combine(Server.MapPath("~/EquipasFotos/"), nomeAntigo));
                    }
                    
                    return RedirectToAction("Details", "Equipas", new { id = equipa.ID });
                }
                catch (Exception)
                {
                    // caso haja um erro deve ser enviada uma mensagem para o utilizador
                    ModelState.AddModelError("", string.Format("Ocorreu um erro com a edição dos dados da noticia {0}", equipa.Nome));
                }
            }
            return View(equipa);
        }

        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}
    

HockeyPT/HockeyPT/Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HockeyPT.Models;
using IdentitySample.Models;
using PagedList;
using PagedList.Mvc;
namespace HockeyPT.Controllers
{

    public class NoticiasController : Controller
    {

        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Noticias
        public ActionResult Index(int? page)
        {
            var pageNumber = page ?? 1;
            var pageSize = 6;
            return View(db.Noticias.OrderByDescending(x => x.ID).ToPagedList(pageNumber, pageSize));

        }
        public ActionResult Sobre()
        {
            return View();
        }
        //******************************************DETAILS*******************************************************
        // GET: Noticias/Details/5
        /// <summary>
        /// Método que apresentar os detalhes das equipas
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return RedirectToAction("Index");
            }

            Noticias noticias = db.Noticias.Find(id);
            if (noticias == null)
            {
                return RedirectToAction("Index");
            }
            return View(noticias);
        }

        //POST: Noticias/Detail/
        /// <summary>
        /// POST: Noticias/Details/
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Moderador, UtilizadorLogado")]
        public ActionResult Details(int id, string ComentarioBox)
        {
            Comentarios comentario = new Comentarios();
            comentario.DataComentario = DateTime.Now;
            comentario.NoticiaPK = id;
            comentario.Texto = ComentarioBox;
            //permite ir buscar o id do utilizador que esta logado e que faz o comentario
            comentario.UtilizadorPK = db.Utilizadores.Where(model => model.Username == User.Identity.Name).FirstOrDefault().ID;

            if (comentario.Texto == "")
            {
                return RedirectToAction("Details");
            }

            if (ModelState.IsValid)
            {
                db.Comentarios.Add(comentario);
                db.SaveChanges();
                return RedirectToAction("Details");
            }
            return View(comentario);

        }


        //**************************************CREATE***********************************************************
        // GET: Noticias/Create
        /// <summary>
        /// GET: Noticias/Create
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "Administrador, Moderador")]
        public ActionResult Create()
        {
            ViewBag.listaEquipas = db.Equipas.ToList();
            return View();
        }

        // POST: Noticias/Create
        /// <summary>
        /// Método que permite criar uma notícia
        /// </summary>
        /// <param name="noticias"></param>
        /// <param name="ficheiroFotoNoticia"></param>
        /// <param name="checkBoxEquipas"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Titulo,Conteudo,Fotografia")] Noticias noticias,
                            HttpPostedFileBase ficheiroFotoNoticia,
                            string[] checkBoxEquipas)
        {
            var idNovaNoticia = 0;
            ViewBag.listaEquipas = db.Equipas.ToList();
            if (db.Noticias.Count() == 0)
            {
                idNovaNoticia = 1;
            }
            else
            {
                idNovaNoticia = db.Noticias.Max(n => n.ID) + 1;
            }
            noticias.ID = idNovaNoticia;

            noticias.Data = DateTime.Now;

            string nomeCapa = "Noticia" + noticias.ID + ".jpg";
            string caminhoFotografia = "";


            //verificar se chega efetivamente um ficheiro ao servidor
            if (ficheiroFotoNoticia != null)
            {
                //verifica se o ficheiro é uma imagem
                if (ficheiroFotoNoticia.ContentType.Contains("image"))
                {
                    //definir o nome da foto
                    noticias.Fotografia = nomeCapa;
                    //guardar na variavel auxiliar o caminho para onde guardar a imagem
                    caminhoFotografia = Path.Combine(Server.MapPath("~/NoticiasFotos/"), nomeCapa);
                }

            }
            //não foi inserido nenhum ficheiro 
            else
            {
                //gera mensagem de erro
                ModelState.AddModelError("", "Não foi inserida uma imagem");
                //redirecionar o utilizador para a View
                return View(noticias);
            }


            //verificar a lista de equipas
            if (checkBoxEquipas != null)
            {
                for (var i = 0; i < checkBoxEquipas.Length; i++)
                {
                    var x = db.Equipas.Find(Int32.Parse(checkBoxEquipas[i]));
                    noticias.ListaDeEquipas.Add(x);

                    x.ListaDeNoticias.Add(noticias);

                }
            }
            else
            {
                ModelState.AddModelError("", "Não foi fornecida nenhuma Equipa!");
                ViewBag.listaEquipas = db.Equipas.ToList();
                return View(noticias);
            }
            noticias.UtilizadorPK = db.Utilizadores.Where(cc => cc.Username.Equals(User.Identity.Name)).FirstOrDefault().ID;
            noticias.IsVisible = true;
            //ModelSatete.IsValid -> confronta os dados fornecidos com o modelo
            //se nao respeitar as regra dos modelo, rejeita os dados
            try
            {
                if (ModelState.IsValid)
                {

                    //adiciona na estrutura de dados, na memoria do servidor, o objeto Jogadores
                    db.Noticias.Add(noticias);
                    //faz commit na base de dados
                    db.SaveChanges();
                    //guarda a imagem no disco rigido
                    ficheiroFotoNoticia.SaveAs(caminhoFotografia);
                    //redireciona o utilizador para a pagina inicial
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                //gera uma mensagem de erro para o utilizador
                ModelState.AddModelError("", "Ocorreu um erro na criação de uma noticia ");
                return RedirectToAction("Index");
            }

            //ViewBag.listaEquipas = db.Equipas.ToList();
            return View(noticias);
        }

        //************************************************EDIT************************************************
        // GET: Noticias/Edit/5
        /// <summary>
        ///  GET: Noticias/Edit/5
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [Authorize(Roles = "Administrador, Moderador")]
        public ActionResult Edit(int? id)
        {
            Session["id"] = id;
            ViewBag.listaEquipas = db.Equipas.ToList();
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Noticias noticias = db.Noticias.Find(id);
            if (noticias == null)
            {
                return RedirectToAction("Index");
            }
            return View(noticias);
        }

        // POST: Noticias/Edit/5
        /// <summary>
        /// Método que permite editar uma notícia
        /// </summary>
        /// <param name="formulario"></param>
        /// <param name="carregaFotoNoticia"></param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Moderador")]
        public ActionResult Edit(FormCollection formulario,
                            HttpPostedFileBase carregaFotoNoticia)
        {
            Noticias noticia = db.Noticias.Find((int)Session["id"]);
            //preencher os campos da noticia com os campos do formulário
            noticia.Titulo = formulario["Titulo"];
            noticia.Conteudo = formulario["Conteudo"];

            //Preencher a data com o dia em que a noticia foi alterada
            noticia.Data = DateTime.Now;

            // preencher o autor com o utilizador que está autenticado
            var idUtilizador = db.Utilizadores.Where(d => d.Username == User.Identity.Name).FirstOrDefault();
            noticia.UtilizadorPK = idUtilizador.ID;

            //variaveis auxiliares para tratamento da Foto
            string caminhoNoticia = "";
            string nomeAntigo = formulario["Fotografia"];
            //verificação se foi inserido algum ficheiro
            if (carregaFotoNoticia != null)
            {
                string nomeFotografia = "Noticia" + noticia.ID + DateTime.Now.ToString("_yyyyMMdd_hhmmss") + Path.GetExtension(carregaFotoNoticia.FileName).ToLower();
                //verificar se o ficheiro inserido é uma imagem
                if (carregaFotoNoticia.ContentType.Contains("image"))
                {
                    noticia.Fotografia = nomeFotografia;
                    caminhoNoticia = Path.Combine(Server.MapPath("~/NoticiasFotos/"), nomeFotografia);
                    carregaFotoNoticia.SaveAs(Path.Combine(Server.MapPath("~/NoticiasFotos/"), nomeFotografia));

                    //Apagar no disco a imagem
                    System.IO.File.Delete(Path.Combine(Server.MapPath("~/NoticiasFotos/"), nomeAntigo));
                }
            }
            //ficheiro nao inserido

HockeyPT/HockeyPT/Views/Equipas/Create.cshtml
[Autorize]
@model HockeyPT.Models.Equipas

@{
    ViewBag.title="Create";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Create", "Equipas", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Equipas</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
                </div>
            </div>
           
            <div class="form-group">
                @Html.LabelFor(model => model.Logotipo, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                   <input type="file"
                          name="ficheiroLogotipo"
                          style="color:blue"
                          accept=".jpg"/>
                    @Html.ValidationMessageFor(model => model.Logotipo, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
                </div>
            </div>

            
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

HockeyPT/HockeyPT/Views/Equipas/Delete.cshtml
@model HockeyPT.Models.Equipas

@{
    ViewBag.Title = "Delete";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>De certeza que quer eliminar?</h3>
    <div>
        <h4>Equipas</h4>
        <hr />
        @* HTML Helper para apresentar mensagens de erro*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Nome)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Nome)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Logotipo)
                <a href="~/EquipasFotos/" target="_blank">
                    <img src="~/EquipasFotos/" width="50" height="37" />
            </dt>

            <dt>
                @Html.DisplayNameFor(model => model.Cidade)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Cidade)
            </dd>

        </dl>

        @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Index", "Noticias", new { id = Model.ID })'"> Voltar ao Inicio </button>
        </div>
}
    </div>
</body>
</html>

HockeyPT/HockeyPT/Views/Equipas/Details.cshtml
@model HockeyPT.Models.Equipas

@{
    ViewBag.Title = "Details";
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <div class="text-center">
            <h1 style="font-family:Verdana, Geneva, Tahoma, sans-serif;color: grey">@Html.DisplayFor(model => model.Nome) - @Html.DisplayFor(model => model.Cidade)</h1>
        </div>
        <div class="container">
            <div class="row">
                <hr class="estilo1">
                <br>
            </div>

        </div>

        <div class="text-center">
            <img src="~/EquipasFotos/@Model.Logotipo" style="width:250px; height:250px; align-items:center" />
        </div>
        @if (User.IsInRole("Administrador"))
        {
        <div>
            <button type="button" class="btn btn-default" onclick=" location.href='@Url.Action("Edit", "Equipas", new { id = Model.ID })'">Editar Equipa</button>
        </div>
        }
        <div style="width:100%">

            <h1>Plantel: </h1>

            @foreach (var jogadores in Model.ListaDeJogadores.ToList())
        {

            <div class="col-md-4">
                <div class="img-thumbnail" style="margin-bottom:10px; width:100%; height:100%">
                    <img class="imagemJogador" onclick="location.href='@Url.Action("Details","Jogadores", new { id = jogadores.ID })'" src="~/JogadoresFotos/@Html.DisplayFor(j=>jogadores.Fotografia)" style="width:100%; height:490px" />
                    <div class="caption" style="height:30px">
                        <p style="font-family: 'Arial';font-size:130%;color:black;text-align:center">@Html.DisplayFor(nome => jogadores.Nome)</p>
                    </div>
                </div>
            </div>
    }
        </div>
    </div>



    <br />
    <div style="width:100%; display:flex;" class="row">
        <button type="button" class="btn btn-default" style="margin-bottom:0px; text-align:justify" onclick="location.href='@Url.Action("Index", "Noticias", new { id = Model.ID })'"> Voltar ao Inicio </button>

        <div style="display:flex;">
            @if (User.IsInRole("Administrador") || User.IsInRole("Moderador"))
        {
            <button type="button" class="btn btn-default" onclick=" location.href='@Url.Action("Create", "Jogadores", new { EquipaFK = Model.ID })'">Adicionar um Jogador</button>
    }

        </div>
    </div>





</body>
</html>

HockeyPT/HockeyPT/Views/Equipas/Edit.cshtml
@model HockeyPT.Models.Equipas

@{
    ViewBag.Title = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm("Edit",
                           "Equipas",
                            FormMethod.Post,
                            new { enctype = "multipart/form-data" }))
    
        {
        @Html.AntiForgeryToken()
        
    <div class="form-horizontal">
        <br />
        <h3 style="color:darkcyan"> Editar uma Equipa </h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Logotipo)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Logótipo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @* Mostrar a imagem associada a Equipa *@
                <a href="~/EquipasFotos/@Model.Logotipo" target="_blank">
                    <img src="~/EquipasFotos/@Model.Logotipo" height="150" />
                </a>
                @* procurar a nova imagem*@
                <input type="file" name="novoLogotipo" style="color:blue;" accept=".jpg" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cidade, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cidade, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cidade, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
                <button type="button" class="btn btn-warning" style="margin-bottom:0px; text-align:justify" onclick="location.href='@Url.Action("Details", "Equipas", new { id = Model.ID })'"> Cancelar </button>
            </div>
        </div>
    </div>
        }

</body>
</html>

HockeyPT/HockeyPT/Views/Equipas/Index.cshtml
@model IEnumerable<HockeyPT.Models.Equipas>

@{
    ViewBag.Title = "Equipas";
}

<h1> Lista de Equipas </h1>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
     <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Logotipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th></th>
        </tr>
    
    @foreach (var equipas in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => equipas.Nome)
            </td>
            <td>
                <a href="~/EquipasFotos/@equipas.Logotipo" target="_blank">
                    <img src="~/EquipasFotos/@equipas.Logotipo" width="55" height="70" />
                </a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => equipas.Cidade)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id= equipas.ID }) |
                @Html.ActionLink("Detalhes", "Details", new { id= equipas.ID }) |
                @Html.ActionLink("Apagar", "Delete", new { id= equipas.ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

HockeyPT/HockeyPT/Views/Equipas/ListarEquipas.cshtml
@model IEnumerable<HockeyPT.Models.Equipas>

    @foreach (var equipa in Model)
    {
        <a href="@Url.Action("Details","Equipas",new { id = Html.DisplayFor(i => equipa.ID) })"><img style="height:40px;width:40px; margin:4px" src="~/EquipasFotos/@Html.DisplayFor(e=>equipa.Logotipo)" class=" img-rounded" /></a>
    }